import RenderHitArea from "./Components/RenderStage/RenderHitareaComponent";
import NodeConverter from "./Converters/NodeConverter";
import PositionConverter from "./Converters/PositionConverter";
import DefaultPrimitives from "./Geometry/DefaultPrimitives";
import DefaultMaterial from "./Material/Defaults/DefaultMaterial";
import GLExtRequestor from "./Resource/GLExtRequestor";

import GrimoireInterface from "grimoirejs";
import AssetLoadingManagerComponent from "./Components/AssetLoadingManagerComponent";
import CameraComponent from "./Components/CameraComponent";
import CanvasInitializerComponent from "./Components/CanvasInitializerComponent";
import FullscreenComponent from "./Components/FullscreenComponent";
import GeometryComponent from "./Components/GeometryComponent";
import GeometryRegistoryComponent from "./Components/GeometryRegistoryComponent";
import LoopManagerComponent from "./Components/LoopManagerComponent";
import MaterialComponent from "./Components/MaterialComponent";
import MaterialContainerComponent from "./Components/MaterialContainerComponent";
import MaterialImporterComponent from "./Components/MaterialImporterComponent";
import MeshRendererComponent from "./Components/MeshRendererComponent";
import MouseCameraControlComponent from "./Components/MouseCameraControlComponent";
import RendererComponent from "./Components/RendererComponent";
import RendererManagerComponent from "./Components/RendererManagerComponent";
import RenderingTargetComponent from "./Components/RenderingTargetComponent";
import RenderQuadComponent from "./Components/RenderStage/RenderQuadComponent";
import RenderSceneComponent from "./Components/RenderStage/RenderSceneComponent";
import SceneComponent from "./Components/SceneComponent";
import ColorBufferTextureUpdator from "./Components/Texture/ColorBufferTextureUpdator";
import ConstantSizeResourceResizer from "./Components/Texture/ConstantSizeResourceResizer";
import ImageTextureUpdator from "./Components/Texture/ImageTextureUpdator";
import RenderBufferUpdator from "./Components/Texture/RenderBufferUpdator";
import TextureContainer from "./Components/Texture/TextureContainer";
import VideoTextureUpdator from "./Components/Texture/VideoTextureUpdator";
import ViewportSizeResourceResizer from "./Components/Texture/ViewportSizeResourceResizer";
import TransformComponent from "./Components/TransformComponent";
import CanvasSizeConverter from "./Converters/CanvasSizeConverter";
import GeometryConverter from "./Converters/GeometryConverter";
import MaterialConverter from "./Converters/MaterialConverter";
import RenderingTargetConverter from "./Converters/RenderingTargetConverter";
import TextureConverter from "./Converters/TextureConverter";
import ViewportConverter from "./Converters/ViewportConverter";

export default () => {
  GrimoireInterface.register(async() => {
    GrimoireInterface.registerComponent(AssetLoadingManagerComponent);
    GrimoireInterface.registerComponent(CameraComponent);
    GrimoireInterface.registerComponent(CanvasInitializerComponent);
    GrimoireInterface.registerComponent(FullscreenComponent);
    GrimoireInterface.registerComponent(GeometryComponent);
    GrimoireInterface.registerComponent(GeometryRegistoryComponent);
    GrimoireInterface.registerComponent(LoopManagerComponent);
    GrimoireInterface.registerComponent(MaterialComponent);
    GrimoireInterface.registerComponent(MaterialContainerComponent);
    GrimoireInterface.registerComponent(MaterialImporterComponent);
    GrimoireInterface.registerComponent(MeshRendererComponent);
    GrimoireInterface.registerComponent(MouseCameraControlComponent);
    GrimoireInterface.registerComponent(RenderBufferUpdator);
    GrimoireInterface.registerComponent(RendererComponent);
    GrimoireInterface.registerComponent(RendererManagerComponent);
    GrimoireInterface.registerComponent(RenderQuadComponent);
    GrimoireInterface.registerComponent(RenderSceneComponent);
    GrimoireInterface.registerComponent(SceneComponent);
    GrimoireInterface.registerComponent(ColorBufferTextureUpdator);
    GrimoireInterface.registerComponent(TextureContainer);
    GrimoireInterface.registerComponent(TransformComponent);
    GrimoireInterface.registerComponent(RenderHitArea);
    GrimoireInterface.registerComponent(ImageTextureUpdator);
    GrimoireInterface.registerComponent(VideoTextureUpdator);
    GrimoireInterface.registerComponent(ViewportSizeResourceResizer);
    GrimoireInterface.registerComponent(ConstantSizeResourceResizer);
    GrimoireInterface.registerComponent(RenderingTargetComponent);

    GrimoireInterface.registerConverter("CanvasSize", CanvasSizeConverter);
    GrimoireInterface.registerConverter("Geometry", GeometryConverter);
    GrimoireInterface.registerConverter("Material", MaterialConverter);
    GrimoireInterface.registerConverter("Texture", TextureConverter);
    GrimoireInterface.registerConverter("Texture2D", TextureConverter);
    GrimoireInterface.registerConverter("Viewport", ViewportConverter);
    GrimoireInterface.registerConverter("Node", NodeConverter);
    GrimoireInterface.registerConverter(PositionConverter);
    GrimoireInterface.registerConverter("RenderingTarget", RenderingTargetConverter);

    GrimoireInterface.registerNode("goml", ["CanvasInitializer", "LoopManager", "AssetLoadingManager", "GeometryRegistory", "RendererManager", "Fullscreen"]);
    GrimoireInterface.registerNode("scene", ["Scene"]);
    GrimoireInterface.registerNode("object", ["Transform"]);
    GrimoireInterface.registerNode("camera", ["Camera"], { position: "0,0,10" }, "object");
    GrimoireInterface.registerNode("mesh", ["MaterialContainer", "MeshRenderer"], null, "object");
    GrimoireInterface.registerNode("renderer", ["Renderer"]);
    GrimoireInterface.registerNode("geometry", ["Geometry"]);
    GrimoireInterface.registerNode("texture", ["TextureContainer"]);
    GrimoireInterface.registerNode("image-texture", ["ImageTextureUpdator"], null, "texture");
    GrimoireInterface.registerNode("video-texture", ["VideoTextureUpdator"], null, "texture");
    GrimoireInterface.registerNode("material", ["Material"]);
    GrimoireInterface.registerNode("import-material", ["MaterialImporter"]);
    GrimoireInterface.registerNode("color-buffer", ["ColorBufferTextureUpdator"], null, "texture");
    GrimoireInterface.registerNode("render-buffer", ["RenderBufferUpdator"]);
    GrimoireInterface.registerNode("render-scene", ["RenderScene", "RenderHitArea"], { material: null });
    GrimoireInterface.registerNode("render-quad", ["MaterialContainer", "RenderQuad"], { material: null });
    GrimoireInterface.registerNode("rendering-target", ["RenderingTarget"]);

    DefaultPrimitives.register();
    await DefaultMaterial.register();
    GLExtRequestor.request("OES_texture_float");
  });
};
